# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    # URL publique de l'application (OAuth + Reset Password + emails)
    app.url: '%env(resolve:APP_URL)%'

    # Google OAuth: forcer l'écran "Choisir un compte"
    google.oauth_prompt: 'select_account'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ResetPasswordService:
        arguments:
            $appUrl: '%app.url%'

    App\Service\FaceService:
        public: true

    Symfony\Component\Mailer\MailerInterface: '@mailer.mailer'
