<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG45TNDN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG45TNDN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG45TNDN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG45TNDN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG45TNDN\App_KernelDevDebugContainer([
    'container.build_hash' => 'G45TNDN',
    'container.build_id' => 'cf337970',
    'container.build_time' => 1778659643,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG45TNDN');
