<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGKQqw34\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGKQqw34/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGKQqw34.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGKQqw34\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGKQqw34\App_KernelDevDebugContainer([
    'container.build_hash' => 'GKQqw34',
    'container.build_id' => '2ff4d3e7',
    'container.build_time' => 1772704080,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGKQqw34');
